### ISSUE TITLE
Game-List Feature Parity Checklist

### ISSUE THREAD

**Issue by CuddleBear92** [towerwatchman/Atlas_Csharp#11]
This Github issue is just a checklist to get an overview of the features present in GL that Atlas yet has.
While this is all the key points GL does compared to Atlas, it doesn't mean we should follow them.

- [ ] F95 "Browsing", having metadata and images for titles you have not installed. Pretty much have all the metadata for all the files locally cached in the client for easy use and access. #10 
- [ ] Update filter/notifications. (If latest scraped version value is different than any of the installed versions then count it as out of sync and not the latest!)
- [ ] Multiple full pages that overlay one another (Red X to close down open page. Unsure if this one is really needed)
- [ ] Sort orders! All of them!
- [ ] Tag Searching and additional search options
- [ ] Exclusion Searching -title -creator -tag and so on to exclude said things from search.
- [ ] Right click Thumbnail to install version to said title.
- [ ] #23 
- [ ] #22 
- [ ] Tag list on detail page.
- [ ] Screenshots on detail page.
- [ ] #28 
- [ ] Larger Image Viewer (GL does Full Screen but thats overkill, maybe expand on hover or click?)
- [ ] Table/List View
- [x] Extract Archive on install (individual)
- [ ] Archive Game (zip them up, unsure how many uses this one)
- [ ] Scrape F95 Metadata locally without a metadata server.
- [ ] Refresh/scrape metadata locally on a per title basis (detailed page)
- [ ] Add and download metadata based on F95 thread URL.
- [ ] Copy over Game Save files when installing new version of a game, It does this on a few game engines like RenPy and RPGM. #81 
- [ ] Move installed title to a new location. ![image](https://github.com/KJNeko/Atlas/assets/8496821/9b23b964-d420-4816-8bb5-4ea2bf96cd25)
- [ ] Tag Ratings, (tags can have a rating of 0-10 to indicate how "important" or how in focus it is for that title, for example you could have a tag like "Impressive Graphics" and when its really impressive its a 10 and if its not really that impressive its closer to 0. ![image](https://github.com/KJNeko/Atlas/assets/8496821/8c547212-e090-4924-83f3-cb7795be51a5)
- [ ] Expansive Metadata and interactions on right click, should probably be a hover. ![image](https://github.com/KJNeko/Atlas/assets/8496821/01720c25-6d16-431c-b6e3-40157eeef7bf)
- [ ] Updates Window that lists all the new updates since last Sync, Updates has an Update Overlay and New releases got a New overlay. This window got an easy feature to select all, check off multiple or check off installed or favourite titles only with a single click to open all threads in your default browser. If this is added then feeding it to the MyJdownloader api makes more sense! ![image](https://github.com/KJNeko/Atlas/assets/8496821/887b4164-2908-4ee8-beef-bdc428db2b6b)
- [ ] Automatically Uploads Metadata to the shared Metadata Server for all users.... unsure if this just triggers a new scrape on the metadata server or if metadata is actually pushed as custom tags is not pushed as far is i know, only scraped data. Might be scraped locally and pushed! This is also used to add versions missed by the server for one reason or another!
- [ ] Handling HTML Games with greater care as they are PATH specific when it comes to cookies and cache. Games are installed into a "latest" version no matter what the version is, ignoring the version value. This way its always at the same location and saves works across versions. Side-note, using the delete latest version feature when installing an update breaks all of this in GL and the user needs to be aware of that, delete last version needs to check this so the user dont need to control it every time.
- [ ] Some Stats: ![image](https://github.com/KJNeko/Atlas/assets/8496821/64fa8e40-6ae1-40a1-8891-7296abd01eb5) ![image](https://github.com/KJNeko/Atlas/assets/8496821/f3ddc9ce-4804-4f09-b379-0e5a5bb8851a)
